version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    expose:
      - 3306
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data: